apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-sa
  namespace: monitor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grafana-sc-role
  namespace: monitor
rules:
  - apiGroups: [""]
    resources: ["configmaps"] # 这里只给 configmaps 权限，正如你所愿
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-sc-binding
  namespace: monitor
subjects:
  - kind: ServiceAccount
    name: grafana-sa
    namespace: monitor
roleRef:
  kind: Role
  name: grafana-sc-role
  apiGroup: rbac.authorization.k8s.io
