apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-proxy
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      # æ§åˆ¶ DaemonSet çš„éƒ¨ç½²é€»è¾‘
      envoyDaemonSet:
        pod:
          nodeSelector:
            gateway: "true"
        container:
          image: docker.m.daocloud.io/envoyproxy/envoy:v1.33.0
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      # ğŸ‘‡ ä¿®æ­£åçš„ Service æ³¨è§£ä½ç½®
      envoyService:
        type: LoadBalancer
        annotations:
          lb.kubesphere.io/v1alpha1: openelb
