apiVersion: v1
kind: Secret
metadata:
  name: mysql-exporter-config
  namespace: ops
type: Opaque
stringData:
  # 注意：这里只写账号密码，不要写 host，host 我们在 Deployment 里动态指定
  .my.cnf: |
    [client]
    user=exporter
    password=123456
